# ============================================================================
# CLAUDE CONTEXT - DAG REPOSITORY PROTOCOL
# ============================================================================
# EPOCH: 5 - DAG ORCHESTRATION
# STATUS: Core - Protocol contract for DAG repository operations
# PURPOSE: Define the repository interface used by DAG orchestration engines
#          without importing infrastructure/, preserving the layering rule that
#          core/ must not depend on infrastructure/.
# LAST_REVIEWED: 28 MAR 2026
# EXPORTS: DAGRepositoryProtocol
# DEPENDENCIES: typing, core.models.workflow_enums
# ============================================================================
"""Protocol for DAG repository operations used by orchestration engines."""
from typing import Any, Protocol, runtime_checkable

from core.models.workflow_enums import WorkflowRunStatus, WorkflowTaskStatus


@runtime_checkable
class DAGRepositoryProtocol(Protocol):
    """
    Defines the repository contract used by DAG orchestration engines.

    The concrete implementation is WorkflowRunRepository in infrastructure/.
    This Protocol lives in core/ to avoid a layering violation (core/ must
    not import infrastructure/).
    """

    def get_by_run_id(self, run_id: str) -> Any: ...
    def get_tasks_for_run(self, run_id: str) -> list: ...
    def get_deps_for_run(self, run_id: str) -> list: ...
    def update_run_status(self, run_id: str, status: WorkflowRunStatus) -> bool: ...
    def get_release_for_waiting_run(self, run_id: str) -> dict | None: ...
    def complete_gate_node(self, run_id: str, gate_node_name: str, result_data: dict) -> bool: ...
    def skip_gate_node(self, run_id: str, gate_node_name: str, result_data: dict) -> None: ...
    def promote_task(self, task_instance_id: str, from_status: WorkflowTaskStatus, to_status: WorkflowTaskStatus) -> bool: ...
    def skip_task(self, task_instance_id: str) -> bool: ...
    def fail_task(self, task_instance_id: str, error_details: str) -> None: ...
    def set_params_and_promote(self, task_instance_id: str, params: dict, from_status: WorkflowTaskStatus, to_status: WorkflowTaskStatus) -> bool: ...
    def expand_fan_out(self, template_id: str, children: list, deps: list) -> bool: ...
    def aggregate_fan_in(self, fan_in_id: str, aggregated_result: dict) -> None: ...
