# ============================================================================
# ETL SOURCE FILE TRACKING MODELS
# ============================================================================
# STATUS: Core - General-purpose ETL pipeline tracking
# PURPOSE: Track source files through multi-phase processing (FATHOM, raster, vector)
# LAST_REVIEWED: 03 JAN 2026
# REVIEW_STATUS: Checks 1-7 Applied (Check 8 N/A - no infrastructure config)
# ============================================================================
"""
ETL Source File Tracking Models.

General-purpose ETL tracking table that supports any ETL pipeline type.
Tracks source files through multi-phase processing pipelines.

Design Principles:
    - Single table for ALL ETL types (namespaced by etl_type)
    - Flexible source_metadata JSONB for domain-specific fields
    - Generic phase1/phase2 tracking (most ETLs are 1-2 phases)
    - Proper IaC via Pydantic → SQL generation

Supported ETL Types:
    - fathom: Flood hazard data (2-phase: band stack → spatial merge)
    - raster_v2: General raster processing (future)
    - vector: Vector ETL (future)

Exports:
    EtlSourceFile: General ETL tracking record
"""

from datetime import datetime, timezone
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field, ConfigDict, field_serializer


class EtlSourceFile(BaseModel):
    """
    General ETL source file tracking record.

    Tracks source files from blob storage through multi-phase ETL processing.
    Uses etl_type to namespace different ETL pipelines and source_metadata
    JSONB for domain-specific parsed fields.

    Table: app.etl_source_files

    Example FATHOM record:
        etl_type: "fathom"
        source_blob_path: "FATHOM-3-0-3/.../FLUVIAL_DEFENDED/2020/1in100/n04w006.tif"
        source_metadata: {
            "flood_type": "fluvial",
            "defense": "defended",
            "year": 2020,
            "ssp": null,
            "return_period": "1in100",
            "tile": "n04w006",
            "grid_cell": "n00-n05_w005-w010"
        }
    """

    model_config = ConfigDict(
        extra="forbid",
    )

    @field_serializer(
        'phase1_completed_at', 'phase2_completed_at',
        'created_at', 'updated_at'
    )
    @classmethod
    def serialize_datetime(cls, v: datetime) -> Optional[str]:
        return v.isoformat() if v else None

    # =========================================================================
    # Primary Key (auto-generated by PostgreSQL)
    # =========================================================================
    id: Optional[int] = Field(
        default=None,
        description="Auto-generated primary key"
    )

    # =========================================================================
    # ETL Type Namespace
    # =========================================================================
    etl_type: str = Field(
        ...,
        max_length=64,
        description="ETL pipeline type: fathom, raster_v2, vector, etc."
    )

    # =========================================================================
    # Source File Identification
    # =========================================================================
    source_blob_path: str = Field(
        ...,
        max_length=512,
        description="Full blob path in source container"
    )
    source_container: str = Field(
        ...,
        max_length=100,
        description="Source blob container name"
    )
    file_size_bytes: Optional[int] = Field(
        default=None,
        ge=0,
        description="File size in bytes"
    )

    # =========================================================================
    # Parsed Metadata (flexible JSONB for domain-specific fields)
    # =========================================================================
    source_metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Domain-specific parsed metadata as JSONB"
    )

    # =========================================================================
    # Phase 1 Processing
    # =========================================================================
    phase1_group_key: Optional[str] = Field(
        default=None,
        max_length=150,
        description="Grouping key for phase 1 processing"
    )
    phase1_output_blob: Optional[str] = Field(
        default=None,
        max_length=512,
        description="Output blob path after phase 1"
    )
    phase1_job_id: Optional[str] = Field(
        default=None,
        max_length=64,
        description="Job ID that processed phase 1"
    )
    phase1_completed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when phase 1 completed"
    )

    # =========================================================================
    # Phase 2 Processing (optional, for multi-phase ETLs)
    # =========================================================================
    phase2_group_key: Optional[str] = Field(
        default=None,
        max_length=150,
        description="Grouping key for phase 2 processing"
    )
    phase2_output_blob: Optional[str] = Field(
        default=None,
        max_length=512,
        description="Output blob path after phase 2"
    )
    phase2_job_id: Optional[str] = Field(
        default=None,
        max_length=64,
        description="Job ID that processed phase 2"
    )
    phase2_completed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when phase 2 completed"
    )

    # =========================================================================
    # Timestamps
    # =========================================================================
    created_at: Optional[datetime] = Field(
        default=None,
        description="Record creation timestamp"
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="Record last update timestamp"
    )

    # =========================================================================
    # Convenience Methods for FATHOM
    # =========================================================================
    def get_fathom_field(self, field: str) -> Any:
        """Get a FATHOM-specific field from source_metadata."""
        return self.source_metadata.get(field)

    @property
    def flood_type(self) -> Optional[str]:
        """FATHOM: flood type (fluvial/pluvial/coastal)."""
        return self.source_metadata.get("flood_type")

    @property
    def defense(self) -> Optional[str]:
        """FATHOM: defense status (defended/undefended)."""
        return self.source_metadata.get("defense")

    @property
    def year(self) -> Optional[int]:
        """FATHOM: projection year."""
        return self.source_metadata.get("year")

    @property
    def ssp(self) -> Optional[str]:
        """FATHOM: SSP scenario."""
        return self.source_metadata.get("ssp")

    @property
    def return_period(self) -> Optional[str]:
        """FATHOM: return period."""
        return self.source_metadata.get("return_period")

    @property
    def tile(self) -> Optional[str]:
        """FATHOM: tile coordinate."""
        return self.source_metadata.get("tile")

    @property
    def grid_cell(self) -> Optional[str]:
        """FATHOM: grid cell assignment."""
        return self.source_metadata.get("grid_cell")

    class Meta:
        """Table metadata for SQL generation."""
        table_name = "etl_source_files"
        schema = "app"

        # Unique constraint
        unique_constraints = [
            ("etl_type", "source_blob_path")
        ]

        # Indexes for efficient queries
        indexes = [
            ("etl_type",),
            ("etl_type", "phase1_group_key"),
            ("etl_type", "phase2_group_key"),
        ]

        # Partial indexes for finding unprocessed records
        partial_indexes = [
            {
                "columns": ("etl_type", "phase1_group_key"),
                "where": "phase1_completed_at IS NULL"
            },
            {
                "columns": ("etl_type", "phase2_group_key"),
                "where": "phase1_completed_at IS NOT NULL AND phase2_completed_at IS NULL"
            }
        ]


# Module exports
__all__ = [
    'EtlSourceFile'
]
