"""
ETL Tracking Models.

Pydantic models for ETL pipeline tracking tables. Tracks source files
through multi-phase processing pipelines for idempotent processing.

Features:
    - Inventory of source files from blob storage
    - Phase 1/2 output tracking
    - Idempotent processing (skip already-processed files)
    - Progress monitoring and resumption

Exports:
    EtlFathomRecord: Tracks Fathom flood hazard files through 2-phase ETL
"""

from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict


class EtlFathomRecord(BaseModel):
    """
    Fathom ETL tracking record - maps source TIFs to processed outputs.

    This model represents the app.etl_fathom table which tracks all Fathom
    flood hazard source files through the two-phase processing pipeline.

    Path Structure:
    - Present-day: FLOOD_TYPE/YEAR/RETURN_PERIOD/filename_TILE.tif
    - Future projection: FLOOD_TYPE/YEAR/SSP/RETURN_PERIOD/filename_TILE.tif

    Phase 1 (Band Stacking):
    - Groups 8 return period files per tile+scenario
    - Outputs 1 multi-band COG per group (~500MB each)
    - Group key: tile_floodtype-defense_year[_ssp]

    Phase 2 (Spatial Merge):
    - Groups phase1 outputs by 5×5 degree grid cells
    - Outputs 1 merged COG per grid cell+scenario (~2-3GB each)
    - Group key: gridcell_floodtype-defense_year[_ssp]
    """

    model_config = ConfigDict(
        extra="forbid",
        json_encoders={datetime: lambda v: v.isoformat() if v else None}
    )

    # =========================================================================
    # Primary Key (auto-generated by PostgreSQL)
    # =========================================================================
    id: Optional[int] = Field(
        default=None,
        description="Auto-generated primary key"
    )

    # =========================================================================
    # Source File Identification
    # =========================================================================
    source_blob_path: str = Field(
        ...,
        max_length=512,
        description="Full blob path in source container (e.g., COASTAL_DEFENDED/2020/1in10/...)"
    )
    source_container: str = Field(
        default="bronze-fathom",
        max_length=64,
        description="Source blob container name"
    )
    file_size_bytes: Optional[int] = Field(
        default=None,
        ge=0,
        description="File size in bytes (for estimation)"
    )

    # =========================================================================
    # Parsed Metadata (extracted from blob path)
    # =========================================================================
    flood_type: str = Field(
        ...,
        max_length=20,
        description="Flood type: coastal, fluvial, or pluvial"
    )
    defense: str = Field(
        ...,
        max_length=20,
        description="Defense status: defended or undefended"
    )
    year: int = Field(
        ...,
        ge=2020,
        le=2100,
        description="Projection year: 2020 (present), 2030, 2050, 2080"
    )
    ssp: Optional[str] = Field(
        default=None,
        max_length=10,
        description="SSP scenario: ssp126, ssp245, ssp370, ssp585 (NULL for present-day 2020)"
    )
    return_period: str = Field(
        ...,
        max_length=10,
        description="Return period: 1in5, 1in10, 1in20, 1in50, 1in100, 1in200, 1in500, 1in1000"
    )
    tile: str = Field(
        ...,
        max_length=20,
        description="Tile coordinate: n04w006, s10e020, etc."
    )

    # =========================================================================
    # Phase 1: Band Stacking (8 RPs → 1 multi-band COG)
    # =========================================================================
    # Note: phase1_group_key is GENERATED ALWAYS in PostgreSQL, computed here for convenience
    phase1_group_key: Optional[str] = Field(
        default=None,
        max_length=100,
        description="Computed: tile_floodtype-defense_year[_ssp] (GENERATED in PostgreSQL)"
    )
    phase1_output_blob: Optional[str] = Field(
        default=None,
        max_length=512,
        description="Output blob path in silver-fathom after phase 1 processing"
    )
    phase1_job_id: Optional[str] = Field(
        default=None,
        max_length=64,
        description="Job ID that processed this file in phase 1"
    )
    phase1_processed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when phase 1 processing completed"
    )

    # =========================================================================
    # Phase 2: Spatial Merge (NxN tiles → 1 merged COG per grid cell)
    # =========================================================================
    grid_cell: Optional[str] = Field(
        default=None,
        max_length=30,
        description="Grid cell assignment: n00-n05_w010-w005 (5×5 degree)"
    )
    phase2_group_key: Optional[str] = Field(
        default=None,
        max_length=100,
        description="Group key for phase 2: gridcell_floodtype-defense_year[_ssp]"
    )
    phase2_output_blob: Optional[str] = Field(
        default=None,
        max_length=512,
        description="Output blob path after phase 2 processing"
    )
    phase2_job_id: Optional[str] = Field(
        default=None,
        max_length=64,
        description="Job ID that processed this file in phase 2"
    )
    phase2_processed_at: Optional[datetime] = Field(
        default=None,
        description="Timestamp when phase 2 processing completed"
    )

    # =========================================================================
    # Timestamps
    # =========================================================================
    created_at: Optional[datetime] = Field(
        default=None,
        description="Record creation timestamp (set by database)"
    )
    updated_at: Optional[datetime] = Field(
        default=None,
        description="Record last update timestamp (set by database)"
    )

    # =========================================================================
    # Convenience Methods
    # =========================================================================
    def compute_phase1_group_key(self) -> str:
        """Compute the phase1_group_key value (matches PostgreSQL GENERATED column)."""
        base = f"{self.tile}_{self.flood_type}-{self.defense}_{self.year}"
        if self.ssp:
            return f"{base}_{self.ssp}"
        return base

    class Meta:
        """Table metadata for SQL generation."""
        table_name = "etl_fathom"


# Module exports
__all__ = [
    'EtlFathomRecord'
]
